
pipeline {
  agent { label 'buildnode' }
   environment {
    AWS_ACCOUNT_ID = "942909610557"
    AWS_REGION = "ap-south-1"
    ECR_REPO = "springboot-app"
    IMAGE_TAG = "latest"
   }

  stages {
    stage('Checkout') {
      steps {
        git branch: 'main', credentialsId: 'venu-23', url: 'https://github.com/venu-23/DevSecOPs.git'
      }
    }
  
   stage('Stage I: Build') {
      steps {
        echo "Building Jar Component ..."
        dir('springboot-build-pipeline') {
            sh "export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64; mvn clean package"
        }
      }
    }

   stage('Stage II: Code Coverage ') {
      steps {
	    echo "Running Code Coverage ..."
        dir('springboot-build-pipeline') {
            sh "export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64; mvn clean verify"
        }
      }
    }

   stage('Stage III: SCA') {
      steps { 
        echo "Running Software Composition Analysis using OWASP Dependency-Check ..."
        sh """
    export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
    mvn org.owasp:dependency-check-maven:check \
      -DnvdApiDelay=2500 \
      -DnvdMaxRetryCount=10
    """
      }
    }

   stage('Stage IV: SAST') {
      steps { 
        echo "Running Static application security testing using SonarQube Scanner ..."
        withSonarQubeEnv('mysonarqube') {
            sh 'mvn sonar:sonar -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml -Dsonar.dependencyCheck.jsonReportPath=target/dependency-check-report.json -Dsonar.dependencyCheck.htmlReportPath=target/dependency-check-report.html -Dsonar.projectName=wezvatech'
       }
      }
    }

   stage('Stage V: QualityGates') {
      steps { 
        echo "Running Quality Gates to verify the code quality"
        script {
          timeout(time: 1, unit: 'MINUTES') {
            def qg = waitForQualityGate()
            if (qg.status != 'OK') {
              error "Pipeline aborted due to quality gate failure: ${qg.status}"
            }
           }
        }
      }
    }
   
 stage('Build & Push to ECR') {
    steps {
        withCredentials([[
            $class: 'AmazonWebServicesCredentialsBinding',
            credentialsId: 'aws-creds'
        ]]) {
            script {
                def imageUri = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:${IMAGE_TAG}"

                dir('springboot-build-pipeline') {
                    sh """
                    echo "Login to ECR"
                    aws ecr get-login-password --region ${AWS_REGION} | docker login \
                    --username AWS \
                    --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com

                    echo "Build Docker image"
                    docker build -t ${ECR_REPO}:${IMAGE_TAG} .

                    echo "Tag image"
                    docker tag ${ECR_REPO}:${IMAGE_TAG} ${imageUri}

                    echo "Push image to ECR"
                    docker push ${imageUri}
                    """
                }
            }
        }
    }
}
        
   stage('Stage VII: Scan Image ') {
      steps { 
        echo "Scanning Image for Vulnerabilities"
        sh "trivy image --scanners vuln --offline-scan adamtravis/democicd:latest > trivyresults.txt"
        }
    }
          
   stage('Stage VIII: Smoke Test ') {
      steps { 
        echo "Smoke Test the Image"
        sh "docker run -d --name smokerun -p 8080:8080 adamtravis/democicd"
        sh "sleep 90; ./check.sh"
        sh "docker rm --force smokerun"
        }
    }

  }
}
